### ISSUE TITLE
Proposing a Neo4j client implementation

### ISSUE THREAD

**Issue by elR1co** [reactiverse/reactiverse#10]
### Project name

Vert.x Neo4j Client, artifact identifiers being neo4j-client-*

### Project goal

The client is a wrapper around the Neo4j java driver to integrate with Eclipse Vert.x applications.

### Licensing

Apache License 2.0

### Motivation to the join the reactiverse

Neo4j is a popular graph database and it could be interesting to have an available client for Vert.x users.

### Existing implementation

A prototype is available at https://github.com/Olympe-ch/vertx-neo4j-client

**Comment by vietj** [comment]
@FroMage @jponge @cescoffier @pmlopes @aesteve @romalev The discussion and vote is open.

**Comment by vietj** [comment]
@FroMage @jponge @cescoffier @pmlopes @aesteve @romalev The discussion and vote is open.

**Comment by vietj** [comment]
+1 from me

**Comment by jponge** [comment]
It's a worthy addition here, +1

**Comment by pmlopes** [comment]
👍

**Comment by aesteve** [comment]
Long time since I have used neo4j (licensing :\ ) but yeah sure, if the license allows to develop drivers on-top of the official Java driver (I guess so, they're Apache licensed, right?), so 

+1 

for sure.

**Comment by romalev** [comment]
+1 from me.

**Comment by elR1co** [comment]
> Long time since I have used neo4j (licensing :\ ) but yeah sure, if the license allows to develop drivers on-top of the official Java driver (I guess so, they're Apache licensed, right?), so
> 
> +1
> 
> for sure.

Apache License 2.0 https://github.com/neo4j/neo4j-java-driver/blob/4.0/LICENSE.txt

**Comment by tsegismont** [comment]
Sounds good to me, +1 !

**Comment by vietj** [comment]
vote result:

- @aesteve +1
- @vietj +1
- @jponge +1
- @pmlopes +1
- @romalev +1
- @cescoffier abstain
- @FroMage abstain

Quorum of 50% is reached, so it's a go.

**Comment by vietj** [comment]
repository has been created : https://github.com/reactiverse/neo4j-client
