### ISSUE TITLE
Vert.x JUnit5 extensions proposal

### ISSUE THREAD

**Issue by jponge** [reactiverse/reactiverse#11]
# Project name

reactiverse-junit5-extensions

# Project goal

The goal of this project is to offer additional parameter types of the [vertx-junit5](https://github.com/vert-x3/vertx-junit5) JUnit 5 extension.

The core Vert.x stack focuses on JUnit5 (and RxJava 1+2 injection of `Vertx` contexts), while this project could foster a wider ecosystem of injectable types in tests.

# Licensing

Apache Software License v2.0

# Motivation to the join the reactiverse

Foster a wider ecosystem while keeping the Vert.x core stack focused on the fundamental requirements to write JUnit 5 tests.

# Existing implementation

The https://github.com/vert-x3/vertx-junit5-extensions/tree/master/vertx-junit5-web-client `WebClient` support should be the first contribution.

**Comment by jponge** [comment]
@reactiverse/maintainers please vote

**Comment by jponge** [comment]
@FroMage @vietj @cescoffier @pmlopes @aesteve @romalev

**Comment by pmlopes** [comment]
:+1:

**Comment by tsegismont** [comment]
:+1:

**Comment by aesteve** [comment]
Looks like a very great addition.

Maybe you could clarify the scope just a bit?

Possible hint: every module of the Vert.x Stack? (inject a RedisClient, a CassandraClient, a KafkaClient -> btw injecting a KafkaClient may be really great, and really cumbersome at the same time, for instance for the options like auto_commit, auto_offset_reste, etc.)

Or something even more advanced? (like a property-based generator of HTTP requests, which would be absolutely awesome)

I guess it'd make it easy for future contributors to know what they can expect, contribute to.


Anyway, a big 👍  anything that can make life of developers easier, especially in regard to testing, sounds like a great addition to me.

**Comment by jponge** [comment]
Yes absolutely @aesteve

**Comment by jponge** [comment]
I think this vote passes.

**Comment by vietj** [comment]
+1
