### ISSUE TITLE
Nominate Francesco Guardiani

### ISSUE THREAD

**Issue by jponge** [reactiverse/reactiverse#12]
I would like to nominate Francesco Guardiani (@slinkydeveloper) as a maintainer.

Francesco is the original developer of the JUnit5 WebClient extension that has now been moved over to https://github.com/reactiverse/reactiverse-junit5-extensions

+1 from me, obviously 😉

**Comment by vietj** [comment]
+1 for the kid!

**Comment by tsegismont** [comment]
+1

Le mar. 14 avr. 2020 à 13:48, Julien Viet <notifications@github.com> a
écrit :

**Comment by jponge** [comment]
Done!
