### ISSUE TITLE
Proposal for MDC-style logging project

### ISSUE THREAD

**Issue by tsegismont** [reactiverse/reactiverse#14]
### Project name

`vertx-contextual-logging`. But I have no strong opinion on the name. Suggestions welcome!

### Project goal

https://github.com/tsegismont/vertx-contextual-logging#purpose

> In web application logs, messages come from different users and requests.
> When a problem occurs, it can be difficult to determine which ones are related to the issue, especially under load.
> 
> In traditional Java development models (e.g. Spring or Java EE), the server implements a _one thread per request_ design.
> As a consequence, it is possible to store contextual data in `ThreadLocal` variables and use it when logging.
> Both [`logback`](https://logback.qos.ch/manual/mdc.html) and [`log4j2`](https://logging.apache.org/log4j/2.x/manual/thread-context.html) name this _Mapped Diagnostic Context_ (MDC).
> 
> Vert.x implements [the reactor pattern](http://vertx.io/docs/vertx-core/java/#_reactor_and_multi_reactor).
> In practice, this means many concurrent requests can be handled by the same thread, thus preventing usage of `ThreadLocal`s to store contextual data.
> 
> This project uses an alternative storage method for contextual data and makes it possible to have MDC-style logging in Vert.x applications.
> 

### Licensing

Apache License 2

### Motivation to the join the Reactiverse

I got good feedback both on GH and social networks from developers using it in production. I think it can be helpful to a lot of users and moving it to the Reactiverse would increase awareness about this solution.

### Existing implementation

https://github.com/tsegismont/vertx-contextual-logging

**Comment by jponge** [comment]
+1

The name should not have `vertx` in it, `reactiverse-contextual-logging` is probably a good fit.

**Comment by jponge** [comment]
@reactiverse/maintainers

**Comment by tsegismont** [comment]
Any other opinion?

**Comment by u6f6o** [comment]
+1

This was one of the features I was eagerly waiting for (trace.id logging without full blown jaeger/zipkin). I integrated the lib immediately after I upgraded to 4.0.0.

**Comment by pmlopes** [comment]
:+1: (and I also used the emoji thumbs up on the proposal title)

**Comment by vietj** [comment]
+1

**Comment by tsegismont** [comment]
@jponge do we have a quorum? In this case, what's next? Otherwise, how can we move forward?

**Comment by jponge** [comment]
Please move forward and create the repository
