### ISSUE TITLE
Can this work with logback encoder providers?

### ISSUE THREAD

**Issue by crosleyj** [reactiverse/reactiverse#16]
We use logback for logging and Vertx 4, so I'm trying to follow the instructions here: https://reactiverse.io/reactiverse-contextual-logging/#_logback

However, we also use the logstash-logback-encoder provider pattern: https://github.com/logfellow/logstash-logback-encoder#providers-common-to-loggingevents-and-accessevents

So there's no "pattern" tag as shown in the logback example. Instead, our configuration looks like this... Does anyone know if there's a way to get the ContextualData to show up using this kind of pattern?

```
<appender name="CONSOLEJSON" class="ch.qos.logback.core.ConsoleAppender">
    <target>System.err</target>
    <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
      <jsonFactoryDecorator class="com.logging.OutputDecorator"/>
      <providers>
        <timestamp/>
        <logLevel/>
        <loggerName/>
        <message/>
        <arguments/>
        <context/>
        <throwableClassName/>
        <stackTrace/>
      </providers>
    </encoder>
  </appender>
```

**Comment by crosleyj** [comment]
Nevermind figured it out. Needs to look like this:

```
      <providers>
        <timestamp/>
        <logLevel/>
        <pattern>
          <pattern>
            { "test": "%vcl{test}" }
          </pattern>
        </pattern>
        <loggerName/>
        <message/>
        <arguments/>
        <context/>
        <throwableClassName/>
        <stackTrace/>
      </providers>
```

Based on this documentation: https://github.com/logfellow/logstash-logback-encoder#pattern-json-provider

**Comment by tsegismont** [comment]
Thanks for sharing your solution
