### ISSUE TITLE
Apache Pinot Client

### ISSUE THREAD

**Issue by tsegismont** [reactiverse/reactiverse#18]
Hi @reactiverse/maintainers !

I would like to propose the Vert.x Pinot Client project, with @lucifer4j as maintainer.

@lucifer4j has developed a client during Google Summer of code this year. I've mentored him and I'm confident he can be a good steward for the project.

For those who don't know Apache Pinot, it's a database tailored for analytics on large volumes of data. Pinot has a Java Client but it's not convenient to use in a Vert.x application and the HTTP transport is implemented with async http client, which is not optimal regarding event loop utilization.

@lucifer4j has implemented a transport with the Vert.x Web Client and created a futurized API. And thanks to codegen we get RxJava and Mutiny bindings.

The full story is here: https://vertx.io/blog/soc-vertx-pinot-client/

This proposal obviously gets my :+1: 

Thank you

**Comment by sboeckelmann** [comment]
👍

**Comment by pmlopes** [comment]
👍

**Comment by vietj** [comment]
👍

**Comment by jponge** [comment]
👍

**Comment by tsegismont** [comment]
We have a quorum, thank you @lucifer4j and welcome to the Reactiverse!
