### ISSUE TITLE
Proposing an Elasticsearch client implementation

### ISSUE THREAD

**Issue by jponge** [reactiverse/reactiverse#2]
## Project name

Vert.x Elastic Search Client, artifact identifiers being `vertx-elasticsearch-client-*`.

## Project goal

This client exposes the Elasticsearch Java High Level REST Client for Eclipse Vert.x applications.

## Licensing

ASL v2

## Motivation to the join the reactiverse

I would like to develop the project here as Elasticsearch is a popular service in distributed systems, and this is of interest to the larger Vert.x ecosystem.

## Existing implementation

A prototype is available at https://github.com/jponge/vertx-elasticsearch-client

Interestingly all the code is shims being generated from the Elasticsearch client, and adapting to the asynchronous APIs to the Vert.x threading model.

**Comment by jponge** [comment]
@FroMage @vietj @cescoffier @pmlopes The discussion and vote is open.

**Comment by jponge** [comment]
I obviously refrain from voting since this is my project.

**Comment by vietj** [comment]
before voting I think we need to discuss naming as "vertx-elasticsearch-client" cannot be used :-)

here are a few examples of project I did outside of the vertx umbrella:

- reactive-pg-client (initially vertx-pg-client)
- childprocess-vertx-ext

**Comment by vietj** [comment]
suggestion : maybe we can just use `reactive-elasticsearch-client` like the pg client and make this project also run without vertx (basically it instantiates vertx). The reactive pg client has been adopted in other projects without vertx. It would make sense to me to do the same for this client.

**Comment by jponge** [comment]
Sure 👍 

How about `reactiverse-elasticsearch-client`?

**Comment by vietj** [comment]
I would lean toward `reactive` for using the same pattern than the pg client, but that's only a suggestion.

**Comment by jponge** [comment]
Ok for `reactive-elasticsearch-client`.

**Comment by vietj** [comment]
besides, I think it's a great proposal and a perfect fit for the Reactiverse, so +1

**Comment by FroMage** [comment]
+1 too

**Comment by pmlopes** [comment]
since the umbrella is the reactiverse why not just drop the prefix at all since the coordinates to the artifact would always be:

```
io.reactiverse:elasticsearch-client:X.Y.Z
``` 
?

Besides from that +1

**Comment by jponge** [comment]
Good idea @pmlopes

**Comment by cescoffier** [comment]
+1 to the proposal and to @pmlopes suggestion.

**Comment by jponge** [comment]
Thanks everyone, the vote has passed 👍

**Comment by jponge** [comment]
It will thus be `io.reactiverse:elasticsearch-client-*`

**Comment by vietj** [comment]
so to summarise it would be:

- project name : Reactive Elasticsearch Client
- artifactid : elasticsearch-client-*
- repo name: ???

**Comment by jponge** [comment]
Let's stick to `elasticsearch-client` for the repo name as well.

**Comment by vietj** [comment]
do we have other things to name while we are at it ?

**Comment by jponge** [comment]
There will be `elasticsearch-client-rxjava2` and possibly other artefacts, but that should be it.

**Comment by jponge** [comment]
https://issues.sonatype.org/browse/OSSRH-45004

**Comment by jponge** [comment]
Permission granted, we are good to go.
