### ISSUE TITLE
Proposing Consul based cluster manager.

### ISSUE THREAD

**Issue by romalev** [reactiverse/reactiverse#3]
Project name
-
Vert.x Consul cluster manager, group id: `io.vertx`, artifact id: `vertx-consul-cluster-manager`.

Project goal
- 
Given cluster manager fully relies on consul coordination service and implements vert.x cluster management SPI: (HA, auto discovery of vert.x nodes, auto discovery of event bus subscribers, distributed maps, distributed counters, distributed locks).

Licensing
-
ASL v2

Motivation to the join the reactiverse
- 
I think it would be a great addition to vert.x ecosystem to have this implementation. Consul nowadays is being widely used and it might be really reasonable to utilize Consul for Vert.x cluster management purposes.  

Existing implementation
-
Exists under: https://github.com/romalev/vertx-consul-cluster-manager.

Additional
- 
I wrote an appropriate blog post about this CM implementation: https://github.com/vert-x3/vertx-web-site/pull/306. I think this PR should wait until community decides whether **reactiverse** is good place to host this project. 
I also think it'd be great if someone from vert.x community could review this project.

**Comment by vietj** [comment]
as note : you cannot use the `io.vertx` groupId and shall use instead `io.reactiveverse` although I believe it's optional

**Comment by romalev** [comment]
@vietj `io.reactiveverse` sounds more reasonable to me :). Thanks for pointing this out. I am happy to host the project here. For this I suspect I'll need to become an official project maintainer (I am happy to be the one). The thing is I was unable to spot the information within **reactiverse governance** about how to receive an appropriate access to be able to host the project here.

**Comment by jponge** [comment]
@romalev 

> The thing is I was unable to spot the information within reactiverse governance about how to receive an appropriate access to be able to host the project here.

This is deal with after a project is accepted 😉

**Comment by jponge** [comment]
@romalev So this is a complete implementation, right?

**Comment by romalev** [comment]
@jponge - thanks for the feedback, As far as I am not mistaken, someone must then start the voting. The implementation is complete and fully compliant with vert.x core (3.6.0) cluster management TCK. @jponge, if there's anything one my side to be done - will be happy to handle it. Thanks.

**Comment by jponge** [comment]
@vietj @cescoffier @FroMage @pmlopes May have questions / feedback as well.

**Comment by romalev** [comment]
I am happy to answer/hear them.

**Comment by jponge** [comment]
Other than that, +1 from me.

**Comment by cescoffier** [comment]
+1, would be a good addition.

For my own understanding, what would be the difference with an Hazlecast cluster using: https://github.com/bitsofinfo/hazelcast-consul-discovery-spi. Would it be only the shared data stored in consul instead of in the HZ in-memory data grid?

**Comment by romalev** [comment]
@cescoffier - sounds correct. Locks, counters, maps are backed by consul kv store.

**Comment by romalev** [comment]
@FroMage @pmlopes - your input on this would be highly appreciated.

**Comment by pmlopes** [comment]
:+1:

**Comment by romalev** [comment]
@jponge, can we consider this project as accepted ? Majority of reactiverse voted positively. I'd really like to move the project under <b>reactiverse</b> umbrella ASAP if there are not (won't be) any objections from <b>reactiverse</b> maintainers side.

**Comment by jponge** [comment]
Let's go.

@vietj can onboard you for the Sonatype repo.

We need to fix the repository and artifact name.

How about `io.reactiverse` / `consul-cluster-manager`?

**Comment by romalev** [comment]
`io.reactiverse / consul-cluster-manager` sounds reasonable to me. Already fixed.

**Comment by romalev** [comment]
@jponge how can I get a permission to locate the project here ?

**Comment by jponge** [comment]
@romalev let me invite you to the organisation, then you can either fork or move it here.

**Comment by vietj** [comment]
@romalev what is your current Sonatype JIRA ID ?

**Comment by romalev** [comment]
@vietj, I honestly didn't event have an account in Sonatype Jira, just created one. My username is `romalev`, email: `roman.levytskyi.oss@gmail.com` and full name : `Roman Levytskyi`. Hope you're gonna be able to look me up there.

@jponge, thanks so much for inviting me over. I will get stuff moving starting from Monday.

**Comment by romalev** [comment]
@vietj were you able to look me up in Sonatype JIRA ?

**Comment by vietj** [comment]
yes I asked for you to be added

**Comment by vietj** [comment]
@romalev your account should be able to push to io.reactiverse now

**Comment by romalev** [comment]
@vietj - thanks so much! I was finally able to deploy snapshot artifacts to https://oss.sonatype.org/content/repositories/snapshots/io/reactiverse/. Silly question - how do I get "release" artifacts deployed to https://repo1.maven.org/content/repositories/releases/io/reactiverse/ ? 
Should I follow this procedure  https://central.sonatype.org/pages/ossrh-guide.html ? 
Thanks a lot in advance.

**Comment by vietj** [comment]
yes it's a good idea.

**Comment by romalev** [comment]
Quick update : project has been successfully migrated under `reactiverse` umbrella. Today I've released first version of `consul-cluster-manager` to maven central. I'll keep this issue open for the next day or two and if there are no objections from `reactiverse` officials - I'll get this closed.
