### ISSUE TITLE
Proposing Vert.x-Compliant AWS SDK

### ISSUE THREAD

**Issue by aesteve** [reactiverse/reactiverse#4]
# Project name

Vert.x AWS SDK. Or Reactive AWS SDK.

Coordinates could be like : `io.reactiverse:aws-sdk:1.0.0`

# Project goal

Since AWS SDK has been published in version 2.0, it embraces the non-blocking IO model (through netty). Allowing every Vert.x project to take benefit from the default AWS-SDK methods wihout having to re-implement every http call in a non-blocking way.

The only thing that project does, is providing event-loop context bindings, so that the callback of the AWS call is executed in the same Vert.x event-loop that originated the call.

# Licensing

Apache 2.0

# Motivation to the join the reactiverse

There are a lot of independant projects gravitating around Amazon Web Services and Vert.x, some are still maintained, some have been abandoned (S3 client ?).
Now that AWS embraced NIO & Netty, a few lines of code (so easy maintenance) open a brand new world of use cases : DynamoDB, Kinesis, S3, CloudWatch metrics, AWS-managed ElasticSearch, Redis Elasticache, etc. That's a lot of "Vert.x clients" that would have been a pain to re-implement using Vert.x http client. 

Before publishing it to maven central. I thing it'd be great to have a nice umbrella for the project.

# Existing implementation

https://github.com/aesteve/vertx-aws-sdk . The branch `feature/licensing` contains the Apache 2.0 `LICENSE.md` and the renaming (`io.reactiverse` package and groupId).

**Comment by aesteve** [comment]
The README file contains more information about what the project does, the tests, etc.

Some examples :
https://github.com/kohesive/vertx-kinesis/blob/master/src/main/kotlin/uy/kohesive/vertx/kinesis/impl/KinesisClientImpl.kt is using AWS SDK v1 `KinesisAsyncClient` which is using an internal thread pool, not fully benefiting from non-blocking IOs.

https://github.com/hubrick/vertx-s3-client/blob/master/src/main/java/com/hubrick/vertx/s3/client/S3Client.java is a very nice implementation of AWS S3 client, but the maintainer had to re-implement EVERY method and object of the AWS S3 SDK (ACL, Bucket, etc.) which is a lot of work. The Reactive-AWS-SDK implementation allows to use AWS-SDK methods directly.

https://www.qualtrics.com/eng/vert-x-dynamodb-client/ (very good article btw) describes how painful it can be to re-write an existing AWS-SDK API in a non-blocking way. The user had to re-write headers signature code, etc. A huge pain, but a very nice blog article.

Just Google the name of an Amazon Web Service (S3, CloudWatch, etc.) together with Vert.x and you'll probably find a lot of people either struggling or having to write a lot of (no-longer needed) code :)

**Comment by jponge** [comment]
Sounds like a good fit. +1 from me.

**Comment by vietj** [comment]
+1

**Comment by aesteve** [comment]
Thanks for your feedback !
Let's wait for @FroMage @cescoffier @pmlopes 's feedbacks if they have any.

Then we can discuss about the process of transferring ownership and maven central publishing.

**Comment by tsegismont** [comment]
+1 sounds great to me (I have seen a lot of questions on SO about Vert.x
and AWS)

**Comment by aesteve** [comment]
OK good :)

Let's discuss the modalities then, what would be the preferred medium ? Here ? gitter ? Google Group ?

Among the questions : should I transfer ownership in github ? Fork the repo ? How to setup a proper CI chain to publish to maven snapshots then central ?

Thanks :)

**Comment by pmlopes** [comment]
:+1:

**Comment by vietj** [comment]
@aesteve discussion should happen here so we keep a track where it makes most sense :-)

I think transferring the repo is the most straightforward. For the CI you have access to Travis and likely other CIs enabled in the org, up to you. If you want to publish snapshots you can look at how it is done in the reactive postgres client and just copy it.

**Comment by vietj** [comment]
Also I think we need to grant you access to the reactiverse on Central for publishing releases.

**Comment by vietj** [comment]
I believe we should open a new issue in this repo with a checkbox of items to complete for the hand over

**Comment by aesteve** [comment]
> I believe we should open a new issue in this repo with a checkbox of items to complete for the hand over

Definitely !

I'll take "calm" time on saturday to properly work on the transfer !

**Comment by jponge** [comment]
You can just make a checklist here in a comment :-)

**Comment by aesteve** [comment]
* [ ] Transfer ownership to reactiverse
* [ ] Check travis build is still running for branches and PR
* [ ] Check it doesn't change anything to travis and codecov, update badges
* [ ] Choose a proper snapshot publish strategy (snapshot branch ?, Gradle plugin ? Git tag ?) and setup CI accordingly
* [ ] Check that I can publish snapshots to maven snapshots using the appropriate CI build
* [ ] Choose a proper release strategy (push on master ? Gradle release plugin ?) and setup CI accordingly
* [ ] (probably later, once Junit 5.4 is released) Check that I can publish a release to maven central using the chosen strategy and a CI build (push on master, or whatever)

I'll give the first steps a shot this afternoon.

**Comment by aesteve** [comment]
I was about to open a ticket on JIRA in order to create a maven snapshot release but I realised in the ticket they only ask for the "groupId".
So I stopped there, since I mean there is already a ticket about `io.reactiverse` ?

**Comment by vietj** [comment]
I think I should create the ticket.

Julien

**Comment by aesteve** [comment]
Ok, let me know when it's done (or maybe I'll receive an email notification ?)

**Comment by vietj** [comment]
@aesteve what is your current Sonatype JIRA ID ?

**Comment by aesteve** [comment]
Same as github: aesteve

**Comment by vietj** [comment]
@aesteve your account should be able to push to io.reactiverse now

**Comment by aesteve** [comment]
Thank, I'll be giving it a try this evening. I'll be able to merge https://github.com/reactiverse/aws-sdk/pull/6 , too, since Junit 5.4.0 has been released ! Nice stars alignment :)

**Comment by aesteve** [comment]
Thanks Julien(s) for your help.

We're almost there, just missing the doc + the badges

**Comment by jponge** [comment]
Closing this issue since the project is moving forward.
