### ISSUE TITLE
Enable GH projects

### ISSUE THREAD

**Issue by pmlopes** [reactiverse/reactiverse#6]
I'd like to ~propose~ the enabling of GH projects. This feature can be useful for repo owners to track features/tasks/work.

The word propose is striked out because the feature is already enabled but was not discussed in advance. I vote :+1: anyway!

**Comment by jponge** [comment]
+1 from me

**Comment by tsegismont** [comment]
+1

**Comment by vietj** [comment]
+1

**Comment by jponge** [comment]
I just enabled: `"Enable projects for the organization"`

Individual projects can enable the feature at will.
